In [2]:
import pandas as pd
import numpy as np
df_list =[]
states = ["AL","AK", "AZ", "AR", "CA", "CO", "CT", "DC", "DE", "FL", "GA",
         "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD",
         "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ",
         "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC",
         "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY"]
data = [r"acceptance-rate", r"tuition", r"graduation-rate", r"sat-act-scores", r"student-population"]
for st in states[:5]:
    for dt in data:
        url = f"https://www.collegetuitioncompare.com/compare/tables/?state={st}&factor={dt}"
        response = pd.read_html(url)
        df_list.append(response)
        
len(df_list)

25

In [6]:
Acceptance = []
Tuition = []
Graduation = []
SAT_ACT = []
Students_pop = []
for i in range (0,25,5):
    Acceptance.append(df_list[i][0])
    Tuition.append(df_list[i+1][0])
    Graduation.append(df_list[i+2][0])
    SAT_ACT.append(df_list[i+3][0])
    Students_pop.append(df_list[i+4][0])
for i in range(len(states[:5])):
    Acceptance[i]["State"] = states[i]
    Tuition[i]["State"] = states[i]
    Graduation[i]["State"] = states[i]
    SAT_ACT[i]["State"] = states[i]
    Students_pop[i]["State"] = states[i]

,Unnamed: 0,School Name,Applicants,Admitted,Enrolled,Acceptance Rate,Admission Yield,State
0,NaN,"Arizona Christian University Phoenix, AZ",404,226,156,55.94%,69.03%,AZ
1,NaN,Arizona State University-Downtown Phoenix Pho...,5763,4668,1447,81.00%,31.00%,AZ
2,NaN,"Arizona State University-Polytechnic Mesa, AZ",2604,2161,648,82.99%,29.99%,AZ
3,NaN,"Arizona State University-Skysong Scottsdale, AZ",7481,5087,2391,68.00%,47.00%,AZ
4,NaN,"Arizona State University-Tempe Tempe, AZ",26869,22839,8907,85.00%,39.00%,AZ
5,NaN,"Arizona State University-West Glendale, AZ",2610,2140,663,81.99%,30.98%,AZ
6,NaN,"Carrington College-Phoenix North Phoenix, AZ",143,129,94,90.21%,72.87%,AZ
7,NaN,"Carrington College-Tucson Tucson, AZ",87,76,57,87.36%,75.00%,AZ
8,NaN,"Chamberlain University-Arizona Phoenix, AZ",11,3,2,27.27%,66.67%,AZ
9,NaN,"DeVry University-Arizona Phoenix, AZ",28,27,23,96.43%,85.19%,AZ
10,NaN,Embry-Riddle Aeronautical University-Prescott ...,2859,1916,613,67.02%,31.99%,AZ
11,NaN,"Grand Canyon University Phoenix, AZ",31958,23329,3966,73.00%,17.00%,AZ
12,NaN,"Northern Arizona University Flagstaff, AZ",36831,30570,5808,83.00%,19.00%,AZ
13,NaN,"Prescott College Prescott, AZ",248,236,47,95.16%,19.92%,AZ
14,NaN,"University of Advancing Technology Tempe, AZ",836,694,104,83.01%,14.99%,AZ
15,NaN,"University of Arizona Tucson, AZ",39941,33550,7717,84.00%,23.00%,AZ
16,NaN,Average,9917,7978,2040,80.45%,25.57%,AZ

In [50]:
Acceptance_df = pd.concat(Acceptance)
Tuition_df =  pd.concat(Tuition)
Graduation_df = pd.concat(Graduation)
SAT_ACT_df = pd.concat(SAT_ACT)
Students_pop_df = pd.concat(Students_pop)

In [51]:
Acceptance_df.to_csv("Acceptance.csv")
Tuition_df.to_csv("Tuition.csv")
Graduation_df.to_csv("Graduation.csv")
SAT_ACT_df.to_csv("SAT_ACT.csv")
Students_pop_df.to_csv("Students_pop.csv")